SistemaEspaco/Controllers/DashboardReservaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaEspaco.Models;
using SistemaEspaco.Models.ViewModels;
using System.Threading.Tasks;

namespace SistemaEspaco.Controllers
{
    public class DashboardReservaController : Controller
    {
        private readonly ProjetoEspacoContext _context;

        public DashboardReservaController(ProjetoEspacoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var total = await _context.Reservas.CountAsync();
            var ativas = await _context.Reservas
                .CountAsync(r => r.Situacao == "Ativa");
            var finalizadas = await _context.Reservas
                .CountAsync(r => r.Situacao == "Finalizada");

            var vm = new DashboardReserva
            {
                TotalReservas = total,
                ReservasAtivas = ativas,
                ReservasFinalizadas = finalizadas
            };

            return View(vm);


        }


    }

}

SistemaEspaco/Controllers/EspacoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaEspaco.Models;

namespace SistemaEspaco.Controllers
{
    public class EspacoController : Controller
    {
        private readonly ProjetoEspacoContext _context;

        public EspacoController(ProjetoEspacoContext context)
        {
            _context = context;
        }

        // GET: Espaco
        public async Task<IActionResult> Index()
        {
            return View(await _context.Espacos.ToListAsync());
        }

        // GET: Espaco/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var espaco = await _context.Espacos
                .FirstOrDefaultAsync(m => m.IdEspaco == id);
            if (espaco == null)
            {
                return NotFound();
            }

            return View(espaco);
        }

        // GET: Espaco/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Espaco/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEspaco,Nome,Descricao,Capacidade")] Espaco espaco)
        {
            if (ModelState.IsValid)
            {
                _context.Add(espaco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(espaco);
        }

        // GET: Espaco/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var espaco = await _context.Espacos.FindAsync(id);
            if (espaco == null)
            {
                return NotFound();
            }
            return View(espaco);
        }

        // POST: Espaco/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEspaco,Nome,Descricao,Capacidade")] Espaco espaco)
        {
            if (id != espaco.IdEspaco)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(espaco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EspacoExists(espaco.IdEspaco))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(espaco);
        }

        // GET: Espaco/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var espaco = await _context.Espacos
                .FirstOrDefaultAsync(m => m.IdEspaco == id);
            if (espaco == null)
            {
                return NotFound();
            }

            return View(espaco);
        }

        // POST: Espaco/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var espaco = await _context.Espacos.FindAsync(id);
            if (espaco != null)
            {
                _context.Espacos.Remove(espaco);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EspacoExists(int id)
        {
            return _context.Espacos.Any(e => e.IdEspaco == id);
        }
    }
}

SistemaEspaco/Controllers/ReservaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaEspaco.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace SistemaEspaco.Controllers
{
    public class ReservaController : Controller
    {
        private readonly ProjetoEspacoContext _context;
        private readonly ReservaService _reservaService;

        public ReservaController(
            ProjetoEspacoContext context,
            ReservaService reservaService)
        {
            _context = context;
            _reservaService = reservaService;
        }

        public async Task<IActionResult> Index()
        {
            var agora = DateTime.Now;

            var reservasParaFinalizar = await _context.Reservas
                .Where(r => r.Situacao == "Ativa" && r.DataFim < agora)
                .ToListAsync();

            if (reservasParaFinalizar.Any())
            {
                foreach (var r in reservasParaFinalizar)
                    r.Situacao = "Finalizada";

                await _context.SaveChangesAsync();
            }

            ViewBag.ReservasAtivas = await _context.Reservas
                .CountAsync(r => r.Situacao == "Ativa");

            ViewBag.ReservasFinalizadas = await _context.Reservas
                .CountAsync(r => r.Situacao == "Finalizada");

            ViewBag.ReservasPorEspaco = await _context.Reservas
                .Include(r => r.IdEspacoNavigation)
                .GroupBy(r => r.IdEspacoNavigation.Nome)
                .Select(g => new
                {
                    Espaco = g.Key,
                    Total = g.Count()
                })
                .ToListAsync();

            var reservas = _context.Reservas
                .Include(r => r.IdEspacoNavigation)
                .Include(r => r.IdUsuarioNavigation);

            return View(await reservas.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var reserva = await _context.Reservas
                .Include(r => r.IdEspacoNavigation)
                .Include(r => r.IdUsuarioNavigation)
                .FirstOrDefaultAsync(r => r.IdReserva == id);

            if (reserva == null)
                return NotFound();

            return View(reserva);
        }

        public IActionResult Create()
        {
            ViewData["IdEspaco"] = new SelectList(_context.Espacos, "IdEspaco", "Nome");
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "IdUsuario", "Nome");
            return View();
        }

        [HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Create(
    [Bind("IdUsuario,IdEspaco,DataInicio,DataFim")] Reserva reserva)
{
    if (reserva.IdEspaco == null)
    {
        ModelState.AddModelError("", "Você deve selecionar um espaço.");
    }
    else if (_reservaService.TemConflito(
        reserva.IdEspaco.Value,
        reserva.DataInicio,
        reserva.DataFim))
    {
        ModelState.AddModelError("", "Já existe uma reserva nesse horário.");
    }

    if (reserva.DataFim <= reserva.DataInicio)
    {
        ModelState.AddModelError("", "A data final deve ser maior que a inicial.");
    }

    if (reserva.DataInicio < DateTime.Now)
    {
        ModelState.AddModelError("", "Não é possível reservar datas passadas.");
    }

    if (!ModelState.IsValid)
    {
        ViewData["IdEspaco"] = new SelectList(
            _context.Espacos, "IdEspaco", "Nome", reserva.IdEspaco);

        ViewData["IdUsuario"] = new SelectList(
            _context.Usuarios, "IdUsuario", "Nome", reserva.IdUsuario);

        return View(reserva);
    }

    

        reserva.ValorTotal = _reservaService.CalcularValorReserva(reserva);
    reserva.Situacao = "Ativa";

    _context.Reservas.Add(reserva);
    await _context.SaveChangesAsync();

    return RedirectToAction(nameof(Index));
        }

        //relatorio
        public async Task<IActionResult> RelatorioGeral(DateTime? dataInicio, DateTime? dataFim)
        {
            var query = _context.Reservas
                .Include(r => r.IdEspacoNavigation)
                .Include(r => r.IdUsuarioNavigation)
                .AsQueryable();

            if (dataInicio.HasValue)
                query = query.Where(r => r.DataInicio >= dataInicio.Value);

            if (dataFim.HasValue)
                query = query.Where(r => r.DataFim <= dataFim.Value);

            var reservas = await query.ToListAsync();

            ViewBag.TotalUsuarios = await _context.Usuarios.CountAsync();
            ViewBag.TotalEspacos = await _context.Espacos.CountAsync();
            ViewBag.TotalReservas = reservas.Count;
            ViewBag.ReservasAtivas = reservas.Count(r => r.Situacao == "Ativa");
            ViewBag.ReservasFinalizadas = reservas.Count(r => r.Situacao == "Finalizada");
            ViewBag.FaturamentoTotal = reservas.Sum(r => r.ValorTotal);

            ViewBag.ResumoEspacos = reservas
                .GroupBy(r => r.IdEspacoNavigation.Nome)
                .Select(g => new
                {
                    Espaco = g.Key,
                    TotalReservas = g.Count(),
                    Receita = g.Sum(r => r.ValorTotal)
                })
                .ToList();

            return View(reservas);
        }

        //relatorio
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var reserva = await _context.Reservas.FindAsync(id);
            if (reserva == null)
                return NotFound();

            ViewData["IdEspaco"] = new SelectList(
                _context.Espacos, "IdEspaco", "Nome", reserva.IdEspaco);

            ViewData["IdUsuario"] = new SelectList(
                _context.Usuarios, "IdUsuario", "Nome", reserva.IdUsuario);

            return View(reserva);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("IdReserva,IdUsuario,IdEspaco,DataInicio,DataFim")] Reserva reserva)
        {
            if (id != reserva.IdReserva)
                return NotFound();

            var reservaBanco = await _context.Reservas
                .AsNoTracking()
                .FirstOrDefaultAsync(r => r.IdReserva == id);

            if (reservaBanco == null)
                return NotFound();

            if (_reservaService.TemConflito(
                reserva.IdEspaco.Value,
                reserva.DataInicio,
                reserva.DataFim,
                reserva.IdReserva))
                ModelState.AddModelError("", "Já existe uma reserva nesse horário.");

            if (ModelState.IsValid)
            {
                reserva.Situacao = reservaBanco.Situacao;
                reserva.ValorTotal = reservaBanco.ValorTotal;

                _context.Update(reserva);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdEspaco"] = new SelectList(
                _context.Espacos, "IdEspaco", "Nome", reserva.IdEspaco);

            ViewData["IdUsuario"] = new SelectList(
                _context.Usuarios, "IdUsuario", "Nome", reserva.IdUsuario);

            return View(reserva);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var reserva = await _context.Reservas
                .Include(r => r.IdEspacoNavigation)
                .Include(r => r.IdUsuarioNavigation)
                .FirstOrDefaultAsync(r => r.IdReserva == id);

            if (reserva == null)
                return NotFound();

            return View(reserva);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reserva = await _context.Reservas.FindAsync(id);
            if (reserva != null)
            {
                _context.Reservas.Remove(reserva);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ExportarCalendario(int id)
        {
            var reserva = _context.Reservas
                .Include(r => r.IdEspacoNavigation)
                .Include(r => r.IdUsuarioNavigation)
                .FirstOrDefault(r => r.IdReserva == id);

            if (reserva == null)
                return NotFound();

            var pdf = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header()
                        .Text("Comprovante de Reserva")
                        .FontSize(20)
                        .Bold()
                        .AlignCenter();

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Espaço: {reserva.IdEspacoNavigation.Nome}");
                        col.Item().Text($"Usuário: {reserva.IdUsuarioNavigation.Nome}");

                        col.Item().Text($"Data de Início: {reserva.DataInicio:dd/MM/yyyy HH:mm}");
                        col.Item().Text($"Data de Fim: {reserva.DataFim:dd/MM/yyyy HH:mm}");

                        col.Item().Text($"Situação: {reserva.Situacao}");

                        col.Item().LineHorizontal(1);

                        col.Item().Text($"Valor Total: R$ {reserva.ValorTotal:N2}")
                            .Bold();
                    });

                    page.Footer()
                        .AlignCenter()

SistemaEspaco/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using SistemaEspaco.Areas.Identity.Data
@inject UserManager<TelaLogin> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
    var nomeUsuario = user?.Nome; 
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaEspaco</title>

    <script src="https://cdn.tailwindcss.com/3.3.3"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaEspaco.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.3.5/datatables.min.css" rel="stylesheet" integrity="sha384-Lv8lYSJkh1Hc5kB9lk2YbbGdchMRCuAcwUOYWZ3Q/YIfKNVW+6W+V57wxKNv1D8l" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;900&display=swap" rel="stylesheet" />

    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-image: url('@Url.Content("~/img/fundo.png")');
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }
    </style>
</head>




<body class="text-white">

    <header class="backdrop-blur-xl bg-black/40 border-b border-cyan-300/20 shadow-lg">
        <nav class="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">

            <div class="text-2xl font-extrabold tracking-wide text-cyan-300 drop-shadow-lg">
                Sistema de Espaços
            </div>

            <ul class="hidden md:flex space-x-8 text-lg font-semibold">

                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    <li class="text-cyan-300 font-bold">
                        Olá, @nomeUsuario
                    </li>

                    <li><a asp-controller="Usuario" asp-action="Index" class="hover:text-cyan-300 transition">Usuários</a></li>
                    <li><a asp-controller="Espaco" asp-action="Index" class="hover:text-cyan-300 transition">Espaços</a></li>
                    <li><a asp-controller="Reserva" asp-action="Index" class="hover:text-cyan-300 transition">Reservas</a></li>
                    <li><a asp-controller="DashboardReserva" asp-action="Index" class="hover:text-cyan-300 transition">DashBoard</a></li>

                    <li>
                        <form method="post" asp-area="Identity" asp-page="/Account/Logout" id="logoutForm" class="inline">
                            <button type="submit" class="hover:text-cyan-300 transition">Sair</button>
                        </form>
                    </li>
                }
                else
                {
                    <li><a asp-area="Identity" asp-page="/Account/Login" class="hover:text-cyan-300 transition">Login</a></li>
                    <li><a asp-area="Identity" asp-page="/Account/Register" class="hover:text-cyan-300 transition">Registrar</a></li>
                }
            </ul>

            <img src="/img/logo-jovemtech-vertical.png" class="h-12 drop-shadow-xl" />
        </nav>
    </header>

    <main class="max-w-6xl mx-auto mt-10 mb-20">
        <div class="bg-white/5 backdrop-blur-xl border border-white/10 p-10 rounded-3xl shadow-2xl">
            @RenderBody()
        </div>
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.3.5/datatables.min.js" integrity="sha384-qH0inyYSCOpaLgM/WSarLVnq0ULwworkGFzUI+E6bpx0DUCIsJePT0TRDnLnkcU1" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>